# To use this file, insall the REST Client extension
# vscode:extension/humao.rest-client

# To switch environments:
#  - Ctrl+Alt+E(Cmd+Alt+E for macOS)
#  - Or `Rest Client: Switch Environment` from command palette

# You'll need to switch to either `local` or `vercel` to get started.

@url = http://localhost:8080
@date = 07-25-1988
@year = 1988
@name = Carl Andres

# @name SEARCH_BIRTHDAY_BY_DATE
GET {{url}}/api/birthdays/search/date/{{date}}
###

# @name SEARCH_BIRTHDAY_BY_YEAR
GET {{url}}/api/birthdays/search/year/{{year}}
###

# @name SEARCH_BIRTHDAY_BY_NAME
GET {{url}}/api/birthdays/search/name/{{name}}
###

# @name ADD_BIRTHDAY_ENTRY
POST {{url}}/api/birthdays/add
Content-Type: application/json

{
  "date": "09/12",
  "births": {
    "name": "Carl Andres",
    "year": 1988,
    "description": "Daemon Mailer",
    "extract": "Loquacious mentus. ",
    "link": "https://cnn.com",
    "img": "https://avatars.githubusercontent.com/u/120593297?v=4"
  }
}
###

# @name UPDATE_ENTRY
PATCH {{url}}/api/birthdays/edit/{{name}}
Content-Type: application/json

{
  "link": "https://josh.ass"
}
###

# @name DELETE_BIRTHDAY
DELETE {{url}}/api/birthdays/remove/{{name}}

###

@username = joeyvalley

###
# @name SEE_ALL_USERS
GET {{url}}/users/all
###

###
# @name CREATE_USER
POST {{url}}/api/register
Content-Type: application/json

{
  "name": {
    "firstName": "Joseph",
    "lastName": "Valle"
  },
  "email": "josephrvalle@gmail.com",
  "username": "joeyvalley",
  "password": "stunn1ngB@ll5",
  "dateCreated": "2023-02-23T21:09:03.492+00:00",
  "collection": []
}
###
# @name DELETE_USER_BY_NAME
DELETE {{url}}/user/delete/{{username}}

###